import React from 'react'
import Image from 'next/legacy/image'
import Link from 'next/link'
import { FaGithub } from 'react-icons/fa'
import { AiOutlineExport } from 'react-icons/ai'
import Head from 'next/head'

const ProjectDetail = ({ title, bgimage, icon, icon2, tech, tech2, tech3, urlCode, urlDemo, description }) => {
  return (
    <>
      <Head>
          <title>maxiturchet | Front-End Developer</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
          <link rel="manifest" href="/site.webmanifest"/>
          <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
          <meta name="msapplication-TileColor" content="#da532c"/>
          <meta name="theme-color" content="#ffffff"/>
      </Head>
      <div className='w-full h-full text-white flex flex-col'>
        <div className='w-full h-[30vh] lg:h-[40vh] relative'>
          <div className='absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/80 z-10'/>
          <Image
            className='absolute z-1'
            layout='fill'
            objectFit='cover'
            src={bgimage} 
            alt='bg'
          />
          <div className='absolute top-[70%] max-w-[1400px] w-full left-[50%] right-[50%] translate-y-[-50%] translate-x-[-50%] text-white z-10 p-2'>
              <h2 className='p-2'>{title}</h2>
              <h3 className='p-2'>{tech} / {tech2}</h3>
          </div>
        </div>
      
        <div className='max-w-[1400px] w-full h-full mx-auto flex flex-col justify-between items-start md:px-8 xl:px-0 xl:py-20'>
          <div className='w-full flex flex-col lg:items-center justify-between lg:flex-row items-start p-4 md:px-8'>
            <div className='flex flex-col w-full max-w-[800px] justify-start '>
              <p className='uppercase text-xl tracking-widest text-[#64ffda] pt-10'>Project</p>
              <div className='flex justify-between items-center'>
                <h2 className='py-4'>Overview</h2>
                <div className='flex items-center justify-end lg:pr-20'>
                  <Link href={urlCode}>
                    <FaGithub className='text-[#64ffda] text-xl cursor-pointer mr-4 hover:scale-110 hover:translate-y-[-4px] ease-in-out duration-300' />
                  </Link>
                  <Link href={urlDemo}>
                    <AiOutlineExport className='text-[#64ffda] text-2xl cursor-pointer hover:scale-110 hover:translate-y-[-4px] ease-in-out duration-300' />
                  </Link>
                </div>
              </div>
              <p className='pr-5'>
                {description}
              </p>
            </div>
            <div className='w-full lg:max-w-[300px] flex items-center justify-around shadow-lg shadow-[#64ffda] rounded-xl p-4 my-10 lg:my-0 '>
              <div className='w-full flex flex-col p-2'>
                <p className='text-center text-white font-bold pb-2'>Technologies</p>
                <div className='flex items-center justify-around lg:flex-col max-[450px]:flex-col'>
                  <div className='text-white py-2 flex items-center'>
                    <div className='text-cyan-400'>
                      {icon}
                    </div>
                    <div className='pl-2'>
                      {tech}
                    </div>
                  </div>
                  <div className='text-white py-2 flex items-center'>
                    <div className='text-blue-600'>
                      {icon2}
                    </div>
                    <div className='pl-2'>
                      {tech2}
                    </div>
                  </div>
                  <div className='text-white py-2 flex items-center'>
                    <div>
                      {tech3}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className='pb-10 px-8 pt-5'>
            <Link href='/#projects'>
              <p className='underline cursor-pointer hover:text-[#64ffda]'>Back</p>
            </Link>
            </div>
          </div>
      </div>
    </>
  )
}

export default ProjectDetail