import { useState, useEffect} from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Main from "@/components/Main";
import About from "@/components/About";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 2000);
  }, []);
  return (
    <section>
      <Head>
        <title>maxiturchet | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <section>
        {loading ? (
          <div className=" bg-black fixed top-0 w-screen h-screen flex items-center justify-center z-50">
            <Image
              className="animate-pulse"
              src="/assets/maxiturchet.png"
              alt="logo"
              width="100"
              height="55"
            />
          </div>
        ) : (
          <>
            <Main />
            <About />
            <Projects />
            <Contact />
          </>
        )}
      </section>
    </section>
  );
}
